wechat_id: gh_2119453d90f0 #replace this with your wechat id
help_message: your help message
welcome_message:
  title: 微工大
  picture: https://www.ahut.edu.cn/
  description: 欢迎您关注微工大
  link: linkedme.in/2013/09/25/turoial-to-be-wechat-public-account-developer/
